version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - gofmt
    - revive
    - misspell

  settings:
    govet:
      enable-all: false
    revive:
      severity: warning

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
